### ISSUE TITLE
Prompt a user for their Connect URL

### ISSUE THREAD

**Issue by tnederlof** [dpastoor/wbi#22]
Many users that set up Workbench will also have a Connect server they would like to have set as the default to make it easier on their users deploying to Connect. This step is often missed/not included and wbi is an excellent opportunity to set this from the beginning.

The [Workbench Admin Guide](https://docs.posit.co/ide/server-pro/rstudio_pro_sessions/rstudio_connect_server.html) specifies setting the `default-rsconnect-server` option in `rsession.conf`.

1. Ask if the user has a Connect server they would like to use as the default
2. If they have Connect then prompt for a URL and save that as the `default-rsconnect-server` option

**Comment by samcofer** [comment]
I'm wondering if we should push this issue a little bit: https://github.com/rstudio/rsconnect-jupyter/issues/217

Not sure it's directly related, but seems like it would be a nice quality of life improvement to only need to set this once.

**Comment by tnederlof** [comment]
Good call, I never realized it wasn't pulling from that field. I know there is a big Jupyter Notebook change that just came out that will break this extension going forward. Its prob worth checking with Workbench team what there plans are (is this going to be abandoned for a new package, etc).
