### ISSUE TITLE
Install Workbench from wbi

### ISSUE THREAD

**Issue by tnederlof** [dpastoor/wbi#7]
Currently, wbi expects Workbench to already be installed and performs a check to verify this is the case. Ideally, users would be able to start with a fresh server and have wbi install Workbench automatically. This would require accurate OS detection and dealing with edge cases.

Automating this step will be an important step towards allowing wbi to set up the most common Workbench installations on a fresh server. It can be awkward to require administrators to do some steps first, then download wbi, then follow the prompts. This + the automation of R and Python installs would go a long way toward this goal.

**Comment by dpastoor** [comment]
would you expect this to be an optional step to opt-in to? 

how would this work for offline installation?

**Comment by tnederlof** [comment]
> would you expect this to be an optional step to opt-in to?
> 
> how would this work for offline installation?

Yes, first I think it would make sense to scan and detect if it is installed already and present the versions.
If nothing is detected then offer to install or if not then please install manually and come back.
If Workbench is detected then skip asking for install

Offline is tricky, so far I have considered wbi scope for online install only. It worth thinking about what it would take to make it work for offline as well...
